site_name: seis-lab-data docs
site_url: !ENV [MKDOCS_SITE_URL, 'https://__SITE_URL_PLACEHOLDER__']
repo_url: https://github.com/naturalgis/seis-lab-data
site_author: Equipa NaturalGIS

hooks:
  - mkdocs/mkdocs_hooks.py

nav:
  - Home: index.md
  - Administration Guide: admin-guide.md
  - Test environment: test-environment.md
  - Development: development.md
  - Dataset reference: dataset-reference.md
  - Data domain acronyms: acronyms.md
  - Sample archive structure: sample-archive.md
  - Supported formats: supported-formats.md
  - Writing docs: writing-docs.md

extra_css:
  - stylesheets/styles.css

theme:
  name: material
  custom_dir: mkdocs
  palette:
    primary: blue grey
    accent: pink
  language: en
  features:
    - content.footnote.tooltips
    - header.autohide
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
        - locale: pt
          name: Português
          nav:
            - Início: index.md
            - Guia de administração do sistema: admin-guide.md
            - Guia do ambiente de testes: test-environment.md
            - Guia de desenvolvimento: development.md
            - Referência de dados: dataset-reference.md
            - Formatos suportados: supported-formats.md
            - Guia de escrita de documentação: writing-docs.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
