import logging
import datetime as dt
import re
from typing import Annotated

import pydantic
from typing_extensions import Self

from ..db import models
from ..constants import (
    AssetType,
    SurveyRelatedRecordStatus,
)
from .common import (
    LinkSchema,
    LocalizableDraftDescription,
    LocalizableDraftName,
    LocalizableDraftRelationship,
    PolygonOut,
    PossiblyInvalidPolygon,
    serialize_id,
    serialize_possibly_empty_date,
)
from .filters import TemporalExtentFilterValue
from .identifiers import (
    DatasetCategoryId,
    ProjectId,
    SurveyRelatedRecordId,
    SurveyMissionId,
    RecordAssetId,
    UserId,
    WorkflowStageId,
)
from .surveymissions import SurveyMissionReadEmbedded
from .datasetcategories import DatasetCategoryReadListItem
from .workflowstages import WorkflowStageReadListItem

logger = logging.getLogger(__name__)


def derive_media_type(relative_path: str) -> str | None:
    """Derive an asset's media type from its file extension.

    Follows the `application/prs.ipma.<ext>` convention of the seeded asset
    discovery configurations. Paths with no usable extension have no media type
    to be derived from them, in which case it must be provided explicitly.
    """
    if match := re.search(r"\.([A-Za-z0-9]+)$", relative_path):
        return f"application/prs.ipma.{match.group(1).lower()}"
    return None


class DataRecordAssetCreate(pydantic.BaseModel):
    """Schema for creating an asset that stands for a file in the archive.

    Data assets are created either by users or by the discovery process and they
    always have a path. Assets derived from them are created by the application
    instead - see `DerivedRecordAssetCreate`.
    """

    id: RecordAssetId
    name: LocalizableDraftName
    relative_path: str
    description: LocalizableDraftDescription = pydantic.Field(
        default_factory=LocalizableDraftDescription
    )
    media_type: str | None = None
    links: list[LinkSchema] = []

    @pydantic.model_validator(mode="after")
    def _derive_media_type(self) -> Self:
        # a media type that was not provided is derived from the file extension
        if not self.media_type:
            self.media_type = derive_media_type(self.relative_path)
        return self


class DataRecordAssetUpdate(pydantic.BaseModel):
    id: RecordAssetId
    name: LocalizableDraftName | None = None
    description: LocalizableDraftDescription | None = None
    media_type: str | None = None
    relative_path: str | None = None
    links: list[LinkSchema] | None = None

    @pydantic.model_validator(mode="after")
    def _derive_media_type(self) -> Self:
        # only derive when the caller did send the field (the update form always
        # does, currently as an empty string) - assigning it here would otherwise
        # add it to `model_fields_set` and clobber the stored value, since
        # updates are applied with `exclude_unset`
        if (
            "media_type" in self.model_fields_set
            and not self.media_type
            and self.relative_path is not None
        ):
            self.media_type = derive_media_type(self.relative_path)
        return self


class DerivedRecordAssetCreate(pydantic.BaseModel):
    """Schema for creating an asset which is derived from a record's data.

    Derived assets are generated by the application, never by users, and they
    have no file in the archive - they carry a payload in `data` (a low-res
    raster, a histogram, ...) and/or a simplified geometry in `geog`, given as
    WKT.
    """

    id: RecordAssetId
    name: LocalizableDraftName
    media_type: str
    asset_type: list[AssetType]
    description: LocalizableDraftDescription = pydantic.Field(
        default_factory=LocalizableDraftDescription
    )
    data: bytes | None = None
    geog: str | None = None

    @pydantic.model_validator(mode="after")
    def _check_has_contents(self) -> Self:
        if self.data is None and self.geog is None:
            raise ValueError("Either data or geog must be provided")
        return self


class DerivedRecordAssetUpdate(pydantic.BaseModel):
    id: RecordAssetId
    name: LocalizableDraftName | None = None
    description: LocalizableDraftDescription | None = None
    media_type: str | None = None
    asset_type: list[AssetType] | None = None
    data: bytes | None = None
    geog: str | None = None


class RecordAssetReadListItem(pydantic.BaseModel):
    id: Annotated[RecordAssetId, pydantic.PlainSerializer(serialize_id)]
    name: LocalizableDraftName
    asset_type: list[AssetType]
    is_valid: bool


class RecordAssetReadDetailEmbedded(RecordAssetReadListItem):
    description: LocalizableDraftDescription
    relative_path: str | None
    media_type: str | None
    links: list[LinkSchema] = []


class SurveyRelatedRecordReadEmbedded(pydantic.BaseModel):
    id: Annotated[SurveyRelatedRecordId, pydantic.PlainSerializer(serialize_id)]
    name: LocalizableDraftName
    status: SurveyRelatedRecordStatus
    validation_result: models.ValidationResult | None
    bbox_4326: PolygonOut | None
    temporal_extent_begin: Annotated[
        dt.date | None, pydantic.PlainSerializer(serialize_possibly_empty_date)
    ]
    temporal_extent_end: Annotated[
        dt.date | None, pydantic.PlainSerializer(serialize_possibly_empty_date)
    ]
    survey_mission: SurveyMissionReadEmbedded

    @classmethod
    def from_db_instance(
        cls, instance: models.SurveyRelatedRecord
    ) -> "SurveyRelatedRecordReadEmbedded":
        return cls(
            **instance.model_dump(),
            survey_mission=SurveyMissionReadEmbedded.from_db_instance(
                instance.survey_mission
            ),
        )


def check_asset_english_names_for_uniqueness(
    assets: list[DataRecordAssetCreate] | list[DataRecordAssetUpdate],
) -> list[DataRecordAssetCreate] | list[DataRecordAssetUpdate]:
    seen_names = set()
    for asset in assets:
        if asset.name is None:  # not being changed, so nothing to check here
            continue
        if asset.name.en in seen_names:
            raise ValueError(f"Duplicate asset english name found: {asset.name.en!r}")
        seen_names.add(asset.name.en)
    return assets


class RelatedRecordCreate(pydantic.BaseModel):
    related_record_id: SurveyRelatedRecordId
    relationship: LocalizableDraftRelationship


class SurveyRelatedRecordCreate(pydantic.BaseModel):
    id: SurveyRelatedRecordId
    owner_id: UserId
    survey_mission_id: SurveyMissionId

    name: LocalizableDraftName
    description: LocalizableDraftDescription
    dataset_category_id: DatasetCategoryId
    workflow_stage_id: WorkflowStageId
    bbox_4326: PossiblyInvalidPolygon | None = None
    temporal_extent_begin: dt.date | None = None
    temporal_extent_end: dt.date | None = None
    links: list[LinkSchema] = []
    assets: Annotated[
        list[DataRecordAssetCreate],
        pydantic.AfterValidator(check_asset_english_names_for_uniqueness),
    ] = []
    related_records: list[RelatedRecordCreate] = []
    extra_properties: dict[str, str] | None = None


class SurveyRelatedRecordBulkUpdate(pydantic.BaseModel):
    description: LocalizableDraftDescription | None = None
    dataset_category_id: DatasetCategoryId | None = None
    workflow_stage_id: WorkflowStageId | None = None
    bbox_4326: PossiblyInvalidPolygon | None = None
    temporal_extent_begin: dt.date | None = None
    temporal_extent_end: dt.date | None = None
    related_records: list[RelatedRecordCreate] = []


class SurveyRelatedRecordBulkUpdateSelection(pydantic.BaseModel):
    """Which records a bulk update targets.

    `selected` and the filter/`excluded_record_ids` fields are mutually
    exclusive ways of specifying the target records, mirroring the two
    selection modes offered by the UI - see
    `operations.surveyrelatedrecords.bulk_update_survey_related_records`.

    `survey_mission_id` is an optional additional scope, not a requirement -
    callers that aren't scoped to a single mission (e.g. a future bulk-edit
    entry point on the general record listing) can simply omit it.
    """

    selected: list[SurveyRelatedRecordId] | None = None
    excluded_record_ids: list[SurveyRelatedRecordId] | None = None
    survey_mission_id: SurveyMissionId | None = None
    project_id: ProjectId | None = None
    en_name_filter: str | None = None
    pt_name_filter: str | None = None
    spatial_intersect: PossiblyInvalidPolygon | None = None
    temporal_extent: TemporalExtentFilterValue | None = None
    asset_path_fragment_filter: str | None = None
    asset_media_type_filter: str | None = None
    dataset_category_id: DatasetCategoryId | None = None
    workflow_stage_id: WorkflowStageId | None = None


class SurveyRelatedRecordUpdate(pydantic.BaseModel):
    survey_mission_id: SurveyMissionId | None = None

    name: LocalizableDraftName | None = None
    description: LocalizableDraftDescription | None = None
    dataset_category_id: DatasetCategoryId | None = None
    workflow_stage_id: WorkflowStageId | None = None
    bbox_4326: PossiblyInvalidPolygon | None = None
    temporal_extent_begin: dt.date | None = None
    temporal_extent_end: dt.date | None = None
    links: list[LinkSchema] | None = None
    assets: Annotated[
        list[DataRecordAssetUpdate],
        pydantic.AfterValidator(check_asset_english_names_for_uniqueness),
    ] = []
    related_records: list[RelatedRecordCreate] = []


class SurveyRelatedRecordPublication(pydantic.BaseModel):
    published: bool


class SurveyRelatedRecordReadListItem(pydantic.BaseModel):
    id: Annotated[SurveyRelatedRecordId, pydantic.PlainSerializer(serialize_id)]
    name: LocalizableDraftName
    description: LocalizableDraftDescription
    status: SurveyRelatedRecordStatus
    validation_result: models.ValidationResult | None
    survey_mission: SurveyMissionReadEmbedded
    dataset_category: DatasetCategoryReadListItem | None
    workflow_stage: WorkflowStageReadListItem | None
    bbox_4326: PolygonOut | None
    temporal_extent_begin: Annotated[
        dt.date | None, pydantic.PlainSerializer(serialize_possibly_empty_date)
    ]
    temporal_extent_end: Annotated[
        dt.date | None, pydantic.PlainSerializer(serialize_possibly_empty_date)
    ]
    record_assets: list[RecordAssetReadDetailEmbedded]

    @classmethod
    def from_db_instance(
        cls, instance: models.SurveyRelatedRecord
    ) -> "SurveyRelatedRecordReadListItem":
        return cls(
            **instance.model_dump(),
            survey_mission=SurveyMissionReadEmbedded.from_db_instance(
                instance.survey_mission
            ),
            dataset_category=DatasetCategoryReadListItem.model_validate(
                instance.dataset_category, from_attributes=True
            )
            if instance.dataset_category
            else None,
            workflow_stage=WorkflowStageReadListItem.model_validate(
                instance.workflow_stage, from_attributes=True
            )
            if instance.workflow_stage
            else None,
            record_assets=[
                RecordAssetReadDetailEmbedded.model_validate(
                    db_asset, from_attributes=True
                )
                for db_asset in instance.assets
            ],
        )


class SurveyRelatedRecordReadDetail(SurveyRelatedRecordReadListItem):
    links: list[LinkSchema] = []
    related_to_records: list[
        tuple[LocalizableDraftDescription, SurveyRelatedRecordReadEmbedded]
    ]
    subject_for_records: list[
        tuple[LocalizableDraftDescription, SurveyRelatedRecordReadEmbedded]
    ]

    @classmethod
    def from_db_instance(
        cls,
        instance: models.SurveyRelatedRecord,
        records_related_to: list[tuple[dict, models.SurveyRelatedRecord]],
        records_subject_for: list[tuple[dict, models.SurveyRelatedRecord]],
    ) -> "SurveyRelatedRecordReadDetail":
        return cls(
            **instance.model_dump(),
            survey_mission=SurveyMissionReadEmbedded.from_db_instance(
                instance.survey_mission
            ),
            dataset_category=DatasetCategoryReadListItem.model_validate(
                instance.dataset_category, from_attributes=True
            )
            if instance.dataset_category
            else None,
            workflow_stage=WorkflowStageReadListItem.model_validate(
                instance.workflow_stage, from_attributes=True
            )
            if instance.workflow_stage
            else None,
            record_assets=[
                RecordAssetReadDetailEmbedded.model_validate(
                    db_asset, from_attributes=True
                )
                for db_asset in instance.assets
            ],
            related_to_records=[
                (relation, SurveyRelatedRecordReadEmbedded.from_db_instance(record))
                for relation, record in records_related_to
            ],
            subject_for_records=[
                (relation, SurveyRelatedRecordReadEmbedded.from_db_instance(record))
                for relation, record in records_subject_for
            ],
        )
